### ISSUE TITLE
LLVM version roadmap?

### ISSUE THREAD

**Issue by chippey** [GafferHQ/dependencies#15]
Probably a complicated and hairy subject, but I was wondering if you guys had a roadmap for updating the LLVM dependency Gaffer has?

Asking, as I was interested in throwing my hand in to try adding a SeExpr expression backend to Gaffer, but SeExpr's current version that has JIT and other such goodness wants LLVM >= 3.8.0.  

I'd like to use Gaffer's official dependencies (which on a side note, looks like it matches the VFX reference platform pretty closely, apart from Qt?), so I'll probably hold off for now, but wanted to ask if there's any idea when (if?) you'll update Gaffer's LLVM.

Cheers!
-Matt

**Comment by johnhaddon** [comment]
Gaffer doesn't have a direct dependency on LLVM, but we need it indirectly for OpenShadingLanguage. OpenShadingLanguage still requires LLVM <= 3.5 as far as I understand :

https://github.com/imageworks/OpenShadingLanguage/issues/480

We do try to follow the VFX reference platform as closely as possible, but we're lagging behind on Qt, partly because it has only really been available relatively recently, and partly because in practice many shows are still running on older versions of 3rd party software, which are using Qt 4.8.

Adding SeExpr support would definitely be an interesting project, and it'd be great to see how it turned out. In particular I'd be interested to know what you think the benefits might be over the existing OSL/Python expressions. Folks have mentioned SeExpr in the past, but I've resisted adding it thus far on the grounds that a) OSL has wider uses, since you can also write complete shaders in it and b) I think 3 official languages in one app is plenty (C++, Python, OSL) c) every dependency has a maintenance cost. Without a clear benefit over OSL, I'd be tempted to say I would welcome it as a plugin, but would hesitate to incorporate it into the main package itself.

**Comment by chippey** [comment]
Ah!  Yeah, I actually remember now I saw that last year that OSL was dependant on older LLVM releases (it may have actually been that thread I came upon!).  I should have dug a bit deeper and checked over there to see if that was still the case.  (Poor Larry G!  He seems to be juggling so many things over there!)

A thought occurs that in the meantime, I could just build v3+ of SeExpr with its LLVM backend disabled, and experiment from there.  (It looks like there shouldn't be any differences interfacing with SeExpr with whatever its backend is, so a switch in the future looks like just a recompile of the library?).

No worries on however you'd eventually like it to be available to Gaffer! Advantages I can see though:
-Subjectively, I like SeExpr for whipping out expressions better due to its shorthanded-ness and syntax 
-Has a very nice featured expression editor all ready to go, and it's a uniform interface across applications that use it since it's part of the library
-Has a nice library of handy expressions all ready to go that cover a variety of use cases
-Match results from patterns of geo and maps exported from XGen land

(Getting more spitballing here)
-Would be able to be used with the Disney shader in Appleseed
-Guessing, but in the future, may gain speedy GPU powers of LLVM (Disney lists it as one of the things they're exploring)

(Even bigger spitballing and Wild Mass Guessing for things that may be neat in the far future)
-One workflow that I imagine would be nice for Gaffer, is to be able to procedurally scatter points about a scene on geometry, manipulate them, then generate geo on those points and their attributes.  I think SeExpr would be a good fit to manipulate those points and attributes (both generation and filter/manipulate after the fact), especially made nice with said library of already existing library of expressions.

Apologies for any lack of coherency - I haven't had any tea yet.

**Comment by johnhaddon** [comment]
> A thought occurs that in the meantime, I could just build v3+ of SeExpr with its LLVM backend disabled, and experiment from there. (It looks like there shouldn't be any differences interfacing with SeExpr with whatever its backend is, so a switch in the future looks like just a recompile of the library?).

Sounds like a plan!

>-Subjectively, I like SeExpr for whipping out expressions better due to its shorthanded-ness and syntax
-Has a very nice featured expression editor all ready to go, and it's a uniform interface across applications that use it since it's part of the library
-Has a nice library of handy expressions all ready to go that cover a variety of use cases

Thanks for outlining some of the benefits you see in SeExpr - I made an early decision to back OSL so it's something I'm not as up-to-date with as I could be. Question - does SeExpr allow "shadeops"? As in additional C++ functions that can be injected into the language? That's something I am missing in OSL when it comes to some of the fancier integrations we want to make.

I think the base set of OSL functions is pretty good, but we're definitely lacking a higher level library of things like fbm, Voronoi etc. That's something I hope to add over time - maybe I should take a look at some of SeExpr's builtins to see if following suit might make sense? That might make any transition from one to the other a bit easier?

I do feel though that although SeExpr might be ahead in terms of editors and a standard library, OSL wins big by being able to define entire shaders, by being available in all the major renderers out of the box, by being able to compose shaders visually using node graphs, and by being crazy optimised.

Anyway, I don't want to put you off; having an SeExpr plugin would be great, and I have endeavoured to design the Expression API such that it should be possible. Let me know if there's anything I can help with!

Cheers...
John

**Comment by chippey** [comment]
> Question - does SeExpr allow "shadeops"? As in additional C++ functions that can be injected into the language? That's something I am missing in OSL when it comes to some of the fancier integrations we want to make.

Yup!  In fact, I believe that's how XGen supports texture lookups with OIIO.  (Just checked - yup, in fact the code for that extension is included with maya: under $MAYA_LOCATION/plug-ins/xgen/devkit/xgenSeExpr.  Dunno how updated that source is; headers say 2013).  A fun thing that occurs to me might be to add functionality to query VDB volumes in an SeExpr?  (A different project for another time though!)

>I think the base set of OSL functions is pretty good, but we're definitely lacking a higher level library of things like fbm, Voronoi etc. That's something I hope to add over time - maybe I should take a look at some of SeExpr's builtins to see if following suit might make sense? That might make any transition from one to the other a bit easier?

If you want to take a gander at the builtins of SeExpr, they're laid out here: https://wdas.github.io/SeExpr/doxygen/userdoc.html (and the code here: https://github.com/wdas/SeExpr/blob/master/src/SeExpr/ExprBuiltins.cpp (Which also, somewhat ironically has a few more examples of how to add functions)). Disney's base SeExpr library of expressions is included with Maya, in "$MAYA_LOCATION/plug-ins/xgen/presets/expressions/samples"  (Dunno why Autodesk renamed it to samples).  Quite a lot of stuff in there.

>I think the base set of OSL functions is pretty good, but we're definitely lacking a higher level library of things like fbm, Voronoi etc. That's something I hope to add over time - maybe I should take a look at some of SeExpr's builtins to see if following suit might make sense? That might make any transition from one to the other a bit easier?

I do like SeExpr's noises, and the idea of being to use their implementation (or rather, get the same results) transitioning from one backend to another is attractive.  (I wish there was some sort of common open noise library used across all vfx software!  Ah to dream...).  At a very quick glance, it looks like SeExpr's noises are based on pre-computed tables, while OSL's smaller subset is all calculated on the fly?  I don't know enough to determine which approach is better.  On the converse side however, it would be possible to extend SeExpr with OSL's noise functions...

>I do feel though that although SeExpr might be ahead in terms of editors and a standard library, OSL wins big by being able to define entire shaders, by being available in all the major renderers out of the box, by being able to compose shaders visually using node graphs, and by being crazy optimised.

I definitely agree that writing entire shaders in SeExpr is not a good idea.  However speaking of the context of shading, I think they're kinda nice as an input to shader parameters (made in OSL, or otherwise).  I know this is already possible out of the box in PRMan, indirectly possible with MtoA (via Xgen and arnold aiUserData nodes) and looks like this guy wrote an implementation for direct use with arnold (https://github.com/gatgui/SeExprArnold), and I'm unsure about 3delight (though it might be able to just compile the RenderMan shadeop src that's included with SeExpr?)  No idea about VRay however, though I imagine probably not.
Put another way, in the context of shading, I guess I see SeExpr being complimentary to, rather than replacing OSL.

>Anyway, I don't want to put you off; having an SeExpr plugin would be great, and I have endeavoured to design the Expression API such that it should be possible. Let me know if there's anything I can help with!

Thanks!  And I'm sure I'll have questions in the future.  I'm still groking the Expression API at the moment.  I may ask about GitHub too, if that's alright, as I'm a github newbie in most respects.

Once again, I apologize for any incoherence:  I yet again haven't had my tea yet.

Cheers!
-Matt

**Comment by johnhaddon** [comment]
> Thanks! And I'm sure I'll have questions in the future. I'm still groking the Expression API at the moment. I may ask about GitHub too, if that's alright, as I'm a github newbie in most respects.

Thanks for the info about SeExpr - I'll try to find time to take a good look at those links.

> Once again, I apologize for any incoherence: I yet again haven't had my tea yet.

 No incoherence detected - I reckon you'll get this whipped up in no time once you've had your tea :)

**Comment by johnhaddon** [comment]
I'm going to close this since the LLVM question is answered. Please feel free to continue to use it for SeExpr discussion if you want, or to continue the discussion on the [gaffer-dev](https://groups.google.com/forum/#!forum/gaffer-dev) mailing list.

**Comment by chippey** [comment]
Sounds good!  I'm taking my time at the moment as I've got a few other things going on.  Question about the mailing list though - is it possible to join it without having a google account?

**Comment by johnhaddon** [comment]
I believe so - at least when I scan the list of members I see a bunch that aren't using gmail addresses.

**Comment by chippey** [comment]
Just poking my head in to see if you've seen this recent commit to OSL:
https://github.com/imageworks/OpenShadingLanguage/commit/c87da2afec87817cd3b2b7cafdb5f56e716a2aed

Looks like OSL is working now with LLVM 3.9, and I get the impression that may be the minimum supported in the next major version of OSL?  It appears there's some performance trade offs; some 2x longer compile times, but slightly faster execution.

Cheers!
-Matt

**Comment by johnhaddon** [comment]
Thanks Matt, yep, I'd seen that. I think the latest LLVM/OSL requires C++11 though, so there is still one more hurdle (and I'd like to see if OSL comes up with come compilation speedups first too, since Gaffer's use cases are much more sensitive to compilation speed). Looks like you should be able to make a custom Gaffer build with the latest LLVM right now though, even if it takes a little longer to be the version used in gafferDependencies. How's your SeExpr work looking by the way? Any progress, or anything I can help with?
Cheers...
John
