### ISSUE TITLE
c++11 ABI on gcc versions > 5.1

### ISSUE THREAD

**Issue by ericmehl** [GafferHQ/dependencies#175]
After updating my Linux build chain to the latest [2.1.1 release](https://github.com/GafferHQ/dependencies/releases/tag/2.1.1) (both downloaded from the release page and building it from source) and therefore c++14 in https://github.com/GafferHQ/dependencies/commit/efcc69cd875a545bc294e5905a729b3aed487463, my locally built Cortex and Gaffer no longer run. I'm building from master with gcc 7.5 (presumably anything over 5.1 would fail based on the next paragraphs).

I get unresolved external symbols due to building Boost (and perhaps others, but Boost was the first library loaded that caused the error) in c++14 without the `_GLIBCXX_USE_CXX11_ABI=0` macro set. It is set in [Cortex](https://github.com/ImageEngine/cortex/blob/e5f93a148a523a01b79bfb64ae697af34cc2745c/SConstruct#L1140) and [Gaffer](https://github.com/GafferHQ/gaffer/blob/cf60eb7602cadb1fdb04eb679cfe96c2348d0137/SConstruct#L422) so they were looking for symbols without the `__cxx11` namespace and not finding them.

Commenting those lines out of Cortex and Gaffer builds sorted it for me Gaffer runs as expected (and tests succeed as well).

Is this something I should do a PR for to remove the `_GLIBCXX_USE_CXX11_ABI=0` lines in Cortex and Gaffer Scons? I don't think that would cause problems in pre-5.1 gcc, but not sure if that would run afoul of other solutions IE or others have made.

**Comment by andrewkaufman** [comment]
It's intentional to have those, its specified in the [VFX Platform](https://vfxplatform.com/#footnote-gcc6). I believe boost, etc should all have been built with that set as well. We don't use the dependencies project (releases or build scripts) at IE, but I'm not sure why this that hasn't come up in practice for others...

**Comment by ericmehl** [comment]
Ah, I see now. So maybe I need to add the `_GLIBCXX_USE_CXX11_ABI=0` to Boost and maybe TBB since that was changed in the same commit.

Yes, strange that it hasn't come up elsewhere yet. The CI builds use a pre-5.1 gcc so maybe others haven't hit it yet.

I'll look into it more next week.

**Comment by johnhaddon** [comment]
We (GafferHQ and IE) both build on Centos 7, where the compilers have been built to default to `_GLIBCXX_USE_CXX11_ABI=0`. Other distros have chosen otherwise, so I suspect you're on a distro which defaults to `1`. I'd be happy to accept a PR to add a `CXX11_ABI` boolean argument in the SConstruct, but I think it should default to `0` still.

**Comment by ericmehl** [comment]
Strange, it seems to be building fine for me again now after double checking that I am building from the GafferHQ dependencies. I must have gotten my builds mixed in with the release build which leading to the confusion..

I'm using Ubuntu 18.04 which I'm guessing does what John mentioned and sets `_GLIBCXX_USE_CXX11_ABI=1` by default.

Anyhow, nothing to see here now, and I can continue to make sure my Windows dependency builds aren't breaking Linux.
