### ISSUE TITLE
Include Qt build tools in prebuilt dependencies?

### ISSUE THREAD

**Issue by chippey** [GafferHQ/dependencies#20]
Ahoy!

Got a bit time now to continue on my SeExpr endeavor again.  I was wondering, would it be possible to get the Qt-tools included with the prebuilt dependencies?  (IE, removing '-nomake tools' from buildQt.sh and adding the files to the buildPackage.sh?).

SeExpr uses the cmake build system, and looks like the default cmake module that finds Qt uses qmake to get its bearings, and SeExpr itself needs moc for its editor component.  Without the tools, I can't use the 
packaged precompiled dependencies.  Not a huge deal, as right now I'm able to build the dependencies myself and change the build script to enable the tools, but it'd be nice to save a bit of time to just 
download the packaged build of them you provide. (Although self compiling the dependencies does give me time to make a cup, er pot, of tea in the meantime!)

On an unrelated note, I tried posting this to the gaffer-dev mailing list, but sadly looks like google doesn't allow emailing it without a google account, so looks like I'll just stick to github's systems for now

Cheers!
-Matt

**Comment by johnhaddon** [comment]
I just recently added QtWebKit and QtXML for similar reasons (not needed by Gaffer, useful for 3rd party development), so I'm not against this in principle. The Qt build is a bit of a beast though, and I'm trying to limit the package size if I can. Are you sure that we need to remove `-nomake tools`? I might be wrong, but I think `qmake` and `moc` are build without that, because they're needed by Qt itself? Any chance you could put together a PR with the minimal set of additions you need?

**Comment by chippey** [comment]
Sure!  I could have sworn I didn't see qmake and moc end up in the dest build dir until I removed the `-nomake tools` flag, but it might also have been down to not having `export LD_LIBRARY_PATH=$BUILD_DIR/lib` in the build shell script as well (which I see you've already added to buildQt.sh).  I'll futz with the build flags and env until I get a minimal set.

**Comment by johnhaddon** [comment]
Closing after merging #21. Thanks Matt!

**Comment by chippey** [comment]
Np!
