### ISSUE TITLE
Archives and custom patching

### ISSUE THREAD

**Issue by boberfly** [GafferHQ/dependencies#68]
Hi John,

Just curious with this new approach to packaging up dependencies, what would be the way to apply patches to archives, run a patch diff over the top via the build scripts after extracting? I've had to patch some cmake files (or bring in custom cmake build files) for some of these dependencies on the windows side, or symbol export some internals like with python. Maybe the linux/macOS side doesn't need many custom patches?

Cheers!

**Comment by johnhaddon** [comment]
Hi Alex,

We're starting to use archives now because storing all the source files was making the repository really unwieldy. Another benefit I hadn't considered is that supporting different platforms should be easier with archives, because we can easily store different patches for each platform.

I think there's only one example of patching so far - for [OSL on Mac]( https://github.com/GafferHQ/dependencies/blob/master/build/buildOSL.sh#L22). You should just be able to use `diff` to generate similar patch files for yourself...

Cheers...
John

**Comment by boberfly** [comment]
Hey John,

I've been looking into this [ExternalProject_Add](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) feature of CMake right now and testing a few packages with it. It kind of looks like a nice way of abstracting the system's command line while also benefiting from some of CMake's features, and exporting out a FindXXX.cmake for another library to ingest. Downloading from a url or git cloning external libs is also an option with patching support. You could even clone this dependencies directory into Gaffer for instance and make it a part of Gaffer's (soon-to-be unofficial) CMake build scripts.

I managed to get a dedicated Linux machine again so I can prototype this on there first by porting the exact commands you issue in the shell scripts, I don't have macOS here to test but I'll make sure to add the custom flags for it as well in an OS check.

Cheers

**Comment by johnhaddon** [comment]
Hey Alex,
That looks interesting - thanks for pointing it out. It seems like you still need to provide it with raw commands for the patch and build steps though - there's no magic, right? I'm still somewhat inclined to roll something similar ourselves so we can make it more data-driven and make just the minimal set of features we need, in a scripting language a bit more manageable than CMake. My plan is to try to make a simple prototype of that when I next have to add a new dependency...
Cheers...
John
