### ISSUE TITLE
New build.py config system and Windows

### ISSUE THREAD

**Issue by boberfly** [GafferHQ/dependencies#88]
Hey John,

Just wanted to discuss the new build.py you're prototyping right now in relation to Windows, have a look at:
https://github.com/boberfly/gafferDependencies/commit/9309df7683c00925d5a550c6b8c92fffd2373e46

For an idea of what I'm doing/changing to get it to work. Some of it is a little hacky and I haven't fully run this against my docker container (I'm updating it to incorporate more built-in tools like curl).

Anyways I thought I'd bring it up, I'm trying to use cmake-derived commands as they're platform-independent like:
`cmake --build . --config $CMAKE_BUILD_TYPE --target install -- -j $NUM_PROCESSORS`
Where those env variables are set in build.py and I convert any known $ENV_VAR to %ENV_VAR% for Windows, same for any forward-slashes to back-slashes, and hoping it doesn't break things.

I think this could work for a lot of cmake-derived packages, but for others like Boost and Qt I think I'll just have a separate 'commands_win' key, same for 'environment_win' when needed (eg. everything needs to live in PATH there's no LD_LIBRARY_PATH equivalent).

Cheers...

**Comment by johnhaddon** [comment]
Hi Alex,
It's encouraging that you've managed to get that working! Here's a few thoughts related to your comments :

- I think I'm already making too much use of the environment variables, using them purely for substitutions in places, rather than to set a specific variable that has meaning to the project build. I'm thinking of introducing a new `"variables ": {}` dictionary in the config, and then using those via python string substitutions in the commands, like " -D CMAKE_INSTALL_PREFIX={buildDir}". That should mean you don't need the %ENV_VAR% substitution hack any more. Do you think that will work for you?
- I actually tried to use `cmake --build` at first, because I remembered you'd mentioned it before. Googling suggested that there was no cross-platform way of specifying the number of parallel jobs though, so I backed out. I'd assumed you were using an MSVC builder or something like that, and there the flags are different. But if your builder accepts `-j` then that's great. I'll update to use `cmake --build` when I get a chance.
- Rather than a specific `commands_win` key, I've been thinking of having a more generic way of overriding specific config entries per-platform. So there'd be a "platform:windows" subdict, and I'd overlay anything in there onto the main config. That way you could override everything (downloads, patches, variables etc) on a per-platform basis. How does that sound? 

Thanks for jumping on this so quickly...
Cheers...
John

**Comment by boberfly** [comment]
No worries, it's good to see the new build.py system.

- For the first point I was thinking exactly that, saves the hack workaround.
- Yep the -- is passing the flag directly to the builder so it can error out if the underlying builder doesn't support it, but I've found Qt's drop-in replacement for NMake 'jom' can accept it like regular Make, so far only HDF5 can't build with it but everything else using CMake can. I've been able to get just about everything over to CMake also.
- Yep that sounds good.

One more thing, I was wanting the CMAKE_BUILD_TYPE open for doing debug builds for some dependencies, currently Appleseed crashes the moment you drop in an OSL shader in Gaffer so I think that might be handy to have as an option.

Cheers!

**Comment by boberfly** [comment]
@donboie What's the reasoning, just in case one of the archives goes missing from the source link? Possibly.

I had another thought also, it would be great if each dependency could be installed into separate areas and then merged into the one package at the end, but I know that it would complicate things where one dependency is reliant on another and needs to know where it is, as it won't be in $BUILD_DIR anymore. My reasoning is if this system could be the basis of VFX platform, but that opens a can of worms. Or if you were to build against a DCC app but you just want some deps built that don't come with the DCC. But I guess leave that as a future scope...

**Comment by johnhaddon** [comment]
> What do you think to the idea of storing the packages used for each build in another release called dependency_source, which packages together the archives & scripts so the build can be rerun?

Sounds fine to me.

> I had another thought also, it would be great if each dependency could be installed into separate areas and then merged into the one package at the end

Yeah, I want something along these lines too. Currently each time I do a release I do the entire build of everything, and it's not quick. I'm anticipating adding a "dependencies" field to the config, and also splitting the big manifest from `buildPackage.sh` into individual "manifest" lists in each config. That should give us the foundations for such a feature, or for checkpointing a bit like docker does, which is what I'd been thinking of rather than separate installation areas.

Obviously before any of this can happen, we need to move all the projects over to the new build scheme. I'm aiming to pick these off whenever I have time to spare...

**Comment by johnhaddon** [comment]
Closing, since this isn't really an actionable issue, more a discussion.
